### ISSUE TITLE
So you're setting Primary DNS here ?

### ISSUE THREAD

**Issue by pratikbin** [BudgetSmartHome/home-lab-configs#1]
So you're setting Primary DNS for consul here ? :arrow_down: 
https://github.com/BudgetSmartHome/home-lab-configs/blob/146dd5d4d67e9386c937c349297acdee4b68bd0e/consul.d/config.json#L4

 This is a series of issues :sweat_smile:  which I'll be going to open for my hashi-stack homelab project. I have up and running nomad, consul, traefik, prometheus, grafana and pihole in nomad but so confused at DNS side with consul and pihole 

Im loving this so keep it up

**Comment by proffalken** [comment]
> So you're setting Primary DNS for consul here ?

Nope, this is[ the address that Consul will listen on to respond to DNS queries](https://www.consul.io/docs/agent/options#addresses).

Upstream DNS is set at https://github.com/BudgetSmartHome/home-lab-configs/blob/146dd5d4d67e9386c937c349297acdee4b68bd0e/consul.d/config.json#L44-L47

Glad to hear you're following along!

**Comment by pratikbin** [comment]
:+1:
